.github/workflows/build.from.main.branch.deploy.to.dev.yml
.github/workflows/build.from.release.branch.deploy.to.dev.yml
Dockerfile
api/src/main/resources/application.yaml
tools/openshift/api.dc.yaml

Done with Resource Optmization for EDUC-GRAD-DISTRIBUTION-API

GRAD2-1947 Resouce Optimization

---

api/src/main/java/ca/bc/gov/educ/api/distribution/model/dto/Pen.java
api/src/main/java/ca/bc/gov/educ/api/distribution/service/ReportService.java

Monthly Distribution Run - Labels and School Report Issues

GRAD2-1965

---

api/src/main/java/ca/bc/gov/educ/api/distribution/model/dto/Address.java
api/src/main/java/ca/bc/gov/educ/api/distribution/process/PSIReportProcess.java

GRAD2-1978

---

api/src/main/java/ca/bc/gov/educ/api/distribution/process/BaseProcess.java
api/src/main/java/ca/bc/gov/educ/api/distribution/process/CreateBlankCredentialProcess.java
api/src/main/java/ca/bc/gov/educ/api/distribution/process/CreateReprintProcess.java
api/src/main/java/ca/bc/gov/educ/api/distribution/process/MergeProcess.java
api/src/main/java/ca/bc/gov/educ/api/distribution/process/PSIReportProcess.java

Year-End Disribution run (DISTRUN_YE) - reports School-Level (DISTREP_YE_SC) and District-Level (DISTREP_YE_SD)

GRAD2-1850

---

api/src/main/java/ca/bc/gov/educ/api/distribution/controller/DistributionController.java
api/src/main/java/ca/bc/gov/educ/api/distribution/process/BaseProcess.java

GRAD2-2017: bug fix for missing nongrad distribution run is added into async process.
GRAD2-2101: Monthly Distribution output missing Principal on the address labels

GRAD2-2017: bug fix for missing nongrad distribution run is added into async process.

---

api/pom.xml
api/src/main/java/ca/bc/gov/educ/api/distribution/process/MergeProcess.java

GRAD2-2017: bug fix on 401 error due to the expired token in createSchoolLabelsReport.

GRAD2-2017: bug fix on 401 error due to the expired token in createSchoolLabelsReport.

---

api/src/main/java/ca/bc/gov/educ/api/distribution/service/GradDistributionService.java
api/src/main/java/ca/bc/gov/educ/api/distribution/util/RestUtils.java
api/src/main/resources/application.yaml
api/src/test/resources/application.yaml

GRAD2-2110: added resilience on notifying async dist job is completed.

GRAD2-2110: added resilience on notifying async dist job is completed.

---

api/src/main/java/ca/bc/gov/educ/api/distribution/process/PSIReportProcess.java
api/src/main/java/ca/bc/gov/educ/api/distribution/util/SFTPUtils.java

paper 400 bad request issue is fixed

Grad2-1931

---

api/src/main/java/ca/bc/gov/educ/api/distribution/model/dto/GraduationStatus.java
api/src/main/java/ca/bc/gov/educ/api/distribution/model/dto/Mark.java
api/src/main/java/ca/bc/gov/educ/api/distribution/model/dto/Student.java
api/src/main/java/ca/bc/gov/educ/api/distribution/model/dto/StudentCredentialDistribution.java
api/src/main/java/ca/bc/gov/educ/api/distribution/model/dto/TranscriptCourse.java
api/src/main/java/ca/bc/gov/educ/api/distribution/process/PSIReportProcess.java
api/src/main/java/ca/bc/gov/educ/api/distribution/service/ReportService.java
api/src/main/java/ca/bc/gov/educ/api/distribution/util/EducDistributionApiConstants.java
api/src/test/java/ca/bc/gov/educ/api/distribution/service/DistributionServiceTest.java

Grad2-2182 PSI FTP file changes

---

api/src/main/java/ca/bc/gov/educ/api/distribution/process/PSIReportProcess.java

Empty file issue is fixed for new PEN ofr I36.

Grad2-2182 .DAT file empty issue

---

api/src/main/java/ca/bc/gov/educ/api/distribution/process/MergeProcess.java

GRAD2-2157: task is complete

---

api/src/main/java/ca/bc/gov/educ/api/distribution/model/dto/DistributionResponse.java
api/src/main/java/ca/bc/gov/educ/api/distribution/process/YearEndMergeProcess.java
api/src/main/java/ca/bc/gov/educ/api/distribution/service/PostingDistributionService.java

GRAD2-2298: the issue is resolved.

GRAD2-2298: the issue is resolved.

---

api/src/main/java/ca/bc/gov/educ/api/distribution/process/MergeProcess.java

SUPP: Supplemental Distribution Run - Changes Required

GRAD2-1893

---

api/src/main/java/ca/bc/gov/educ/api/distribution/config/EducDistributionApiConfig.java

Unexpected Internal Server Error for TVRs for Projected Non-Grads

GRAD2-2408

---

api/pom.xml

Sync from main

---

api/src/main/java/ca/bc/gov/educ/api/distribution/process/MergeProcess.java

(GRAD) - P3 Incident: 1950 program includes Non-Completion Reason "506 - N/A"

GRAD2-2477

---

api/src/main/java/ca/bc/gov/educ/api/distribution/model/dto/GradProgram.java

GRAD2-2525: DTO update to sync.

GRAD2-2525: DTO update to sync.

---

api/src/main/java/ca/bc/gov/educ/api/distribution/process/YearEndMergeProcess.java

HD-22859 (GRAD) YE Distribution run should direct Certificates to School at Graduation, not School of Record

GRAD2-2377

---

api/src/main/java/ca/bc/gov/educ/api/distribution/service/SchoolService.java
api/src/main/java/ca/bc/gov/educ/api/distribution/util/EducDistributionApiConstants.java
api/src/main/resources/application.yaml
api/src/test/java/ca/bc/gov/educ/api/distribution/service/SchoolServiceTest.java
api/src/test/resources/application.yaml

Done with endpoint replacements

Grad2-2632 school api call is replaced with trax api.

---

api/src/main/java/ca/bc/gov/educ/api/distribution/process/MergeProcess.java

GRAD2-2590: task is complete.

---

.github/dependabot.yml
.github/workflows/build.from.developer.branch.deploy.to.dev.yml
.github/workflows/build.from.main.branch.deploy.to.dev.yml
.github/workflows/build.from.release.branch.deploy.to.dev.yml

Grad2-3130 ZAPscan version upgraded

---

api/src/main/resources/application.yaml
api/src/test/resources/application.yaml

GRAD2-3162: v2 endpoints are fixed.

GRAD2-3162: v2 endpoints are fixed.

---

api/src/main/java/ca/bc/gov/educ/api/distribution/model/dto/v2/School.java
api/src/main/java/ca/bc/gov/educ/api/distribution/service/ReportService.java
api/src/main/java/ca/bc/gov/educ/api/distribution/service/SchoolService.java
api/src/test/java/ca/bc/gov/educ/api/distribution/controller/DistributionControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/distribution/service/DistributionServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/distribution/service/ReportServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/distribution/service/SchoolServiceTest.java

GRAD2-3163: the null mincode in packing slip is fixed.

GRAD2-3163: the null mincode in packing slip is fixed.

---

.github/workflows/build.from.developer.branch.deploy.to.dev.yml
.github/workflows/build.from.main.branch.deploy.to.dev.yml
.github/workflows/build.from.release.branch.deploy.to.dev.yml
.github/workflows/create_tag.yml
.github/workflows/deploy_prod.yml
.github/workflows/deploy_test.yml
.github/workflows/on.pr.yml
tools/openshift/api.dc.yaml

GRAD2-3109 - Convert Grad Distribution api's Openshift Deployment Config to K8S Deployment

GRAD2-3109 - Convert Grad Distribution api's Openshift Deployment Config to K8S Deployment

---

api/src/main/resources/application.yaml
api/src/test/resources/application.yaml

GRAD-3268 - Monthly cert run failed

GRAD-3268 - Monthly cert run failed

---

api/src/main/resources/application.yaml
api/src/test/resources/application.yaml

GRAD-3268 - Switching endpoints to /search ones

GRAD-3268 - Switching endpoints to /search ones

---

api/src/main/java/ca/bc/gov/educ/api/distribution/service/PostingDistributionService.java
api/src/main/java/ca/bc/gov/educ/api/distribution/util/EducDistributionApiConstants.java
api/src/main/resources/application.yaml
api/src/test/resources/application.yaml

GRAD-3268 - Generating labels file

GRAD-3268 - Generating labels file

---

api/pom.xml
api/src/main/java/ca/bc/gov/educ/api/distribution/config/WebSecurityConfiguration.java
api/src/main/java/ca/bc/gov/educ/api/distribution/controller/APIMetadataController.java

GRAD2-3335 - Add Metadata Endpoint to All GRAD APIs

GRAD2-3335 - Add Metadata Endpoint to All GRAD APIs

---

api/src/main/java/ca/bc/gov/educ/api/distribution/constants/SchoolCategoryCodes.java
api/src/main/java/ca/bc/gov/educ/api/distribution/process/BaseProcess.java
api/src/main/java/ca/bc/gov/educ/api/distribution/process/YearEndMergeProcess.java
api/src/main/java/ca/bc/gov/educ/api/distribution/service/PostingDistributionService.java

- folder structure for indy schools
- only indy_fns students being included in non grad (missing indy)
- missing school address labels

GRAD2-3304 - fixes issues with ye and non grad

---

api/src/main/java/ca/bc/gov/educ/api/distribution/config/EducDistributionApiConfig.java
api/src/main/java/ca/bc/gov/educ/api/distribution/config/RequestResponseInterceptor.java
api/src/main/java/ca/bc/gov/educ/api/distribution/service/RestService.java
api/src/main/java/ca/bc/gov/educ/api/distribution/util/EducDistributionApiConstants.java
api/src/main/java/ca/bc/gov/educ/api/distribution/util/JwtUtil.java
api/src/main/java/ca/bc/gov/educ/api/distribution/util/LogHelper.java
api/src/main/java/ca/bc/gov/educ/api/distribution/util/ThreadLocalStateUtil.java

Grad2-3284 Set Request Headers
